In [39]:
import numpy as np
import pandas as pd

#  Load Data

In [40]:
data = pd.read_csv("output_files/iris.csv")
data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [41]:
data = data[:100]

#### Split data

In [42]:
# Numerical Labels
label_list = list(data['Species'].unique())
y = np.zeros(len(data['Species']))
for i, label in enumerate(data['Species']):
	y[i] = label_list.index(label)
    
# remove old labels
data.pop('Species')
# remove ID
data.pop('Id')
data.shape

# X
X = data.values

In [43]:
y = y.reshape(-1,1)

In [44]:
X.shape, y.shape

((100, 4), (100, 1))

In [85]:
# Shuffle Data
xy = np.hstack((X,y))
np.random.shuffle(xy)
X_shuff = xy[:,:4]
y_shuff =  xy[:,4]

In [86]:
# Train / Test - Data Sets
X_train, y_train = X_shuff[:90], y_shuff[:90]
X_test, y_test = X_shuff[90:], y_shuff[90:]

# Save Data

In [88]:
np.save("data/X_iris_train.npy", X_train)
np.save("data/y_iris_train.npy", y_train)
np.save("data/X_iris_test.npy", X_test)
np.save("data/y_iris_test.npy", y_test)

In [89]:
print(np.load("data/y_iris_test.npy"))

[ 0.  1.  1.  0.  1.  1.  0.  0.  1.  0.]


# Test Classifiers

In [90]:
# Test function
def test_clf_results(y, y_):
    mse = np.mean((y - y_) ** 2)
    n_mclf = len(np.nonzero(y - y_)[0])
    rate_mclf = n_mclf / len(y)
    print("MSE={}, n_MCLF={}, rate_MCFL={}".format(mse, n_mclf, rate_mclf))

### SVM

In [91]:
from sklearn import svm

In [92]:
clf_svm = svm.SVC()
clf_svm.fit(X_train, y_train)  
y_svm = clf_svm.predict(X_test)

In [93]:
test_clf_results(y_test, y_svm)

MSE=0.0, n_MCLF=0, rate_MCFL=0.0


In [94]:
y_test

array([ 0.,  1.,  1.,  0.,  1.,  1.,  0.,  0.,  1.,  0.])

In [95]:
y_svm

array([ 0.,  1.,  1.,  0.,  1.,  1.,  0.,  0.,  1.,  0.])